name: alpha-beta-CROWN
channels:
  - gurobi
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - appdirs
  - blas
  - bottleneck
  - brotli-python
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - cfgv
  - charset-normalizer
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.5.39
  - cuda-runtime=12.1.0
  - cuda-version=12.5
  - distlib
  - ffmpeg
  - filelock
  - freetype
  - gmp
  - gmpy2
  - gnutls
  - gurobi=11.0.2
  - identify
  - idna
  - iniconfig
  - jinja2
  - joblib
  - jpeg
  - lame
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.10.0.4
  - libcurand=10.3.6.39
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libgfortran5
  - libgomp
  - libiconv
  - libidn2
  - libjpeg-turbo
  - libnpp=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libpng
  - libprotobuf
  - libstdcxx-ng
  - libtasn1
  - libtiff
  - libunistring
  - libuuid
  - libwebp-base
  - llvm-openmp
  - lz4-c
  - markdown-it-py
  - markupsafe
  - mdurl
  - mkl  # left unpinned for compatibility unless you need exact mkl versions
  - mkl-service
  - mkl_fft
  - mkl_random
  - mpc
  - mpfr
  - mpmath
  - ncurses
  - nettle
  - networkx
  - nodeenv
  - numexpr
  - onnx
  - openh264
  - openjpeg
  - openssl
  - packaging
  - pandas
  - pillow
  - pip
  - platformdirs
  - pluggy
  - pre-commit
  - psutil
  - pybind11-abi
  - pycparser
  - pygments
  - pysocks
  - pytest
  - python=3.11.9
  - python-dateutil
  - python-tzdata
  - pytorch=2.3.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0=cuda
  - pytz
  - pyyaml
  - readline
  - requests
  - rich
  - scikit-learn
  - scipy
  - setuptools
  - six
  - sortedcontainers
  - sqlite
  - sympy
  - tbb
  - threadpoolctl
  - tk
  - torchaudio=2.3.1
  - torchtriton=2.3.1
  - torchvision=0.18.1
  - tqdm
  - typing-extensions
  - tzdata
  - ukkonen
  - urllib3
  - virtualenv
  - wheel
  - xz
  - yaml
  - zlib
  - zstd
  - numpy-base
  - numpy
  - pip:
      - coloredlogs
      - flatbuffers
      - fsspec
      - humanfriendly
      - git+https://github.com/Verified-Intelligence/onnx2pytorch@325959ed128200459a9634668149a722a6a74797#egg=onnx2pytorch
      - onnxconverter-common
      - onnxoptimizer
      - onnxruntime==1.18.0
      - onnxsim
      - protobuf==3.20.2
      - graphviz
      - skl2onnx
